[package]
name = "gen"
version = "0.1.0"
authors = ["Ethan Brown <ewb@ewb.io>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
ndarray = "0.15"
rand = "0.8"
